package main

import (
	"aprende-golang/internal/service"
	"aprende-golang/internal/store"
	"aprende-golang/internal/transport"
	"context"
	"database/sql"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
	_ "github.com/mattn/go-sqlite3"

	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
)

func main() {
	//conectar a la base: DATABASE_URL definida → Postgres (Render), sin definir → SQLite local
	dsn := os.Getenv("DATABASE_URL")
	driver := "sqlite3"
	if dsn == "" {
		dsn = "./frases.db"
	} else {
		driver = "pgx"
	}
	db, err := sql.Open(driver, dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	//fallar rápido si la base no responde (5s)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := db.PingContext(ctx); err != nil {
		if os.Getenv("DATABASE_URL") != "" {
			log.Fatalf("no se pudo conectar a Postgres (DATABASE_URL): %v", err)
		}
		log.Fatalf("no se pudo conectar a SQLite (./frases.db): %v", err)
	}

	//crear el table si no existe.
	var q string
	if driver == "pgx" {
		q = `
			CREATE TABLE IF NOT EXISTS frases (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			frase TEXT NOT NULL,
			original TEXT NOT NULL,
			autor TEXT NOT NULL,
			categoria TEXT NOT NULL
		)
	`
	} else {
		q = `
			CREATE TABLE IF NOT EXISTS frases (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			frase TEXT NOT NULL,
			original TEXT NOT NULL,
			autor TEXT NOT NULL,
			categoria TEXT NOT NULL
		)
	`
	}
	if _, err := db.Exec(q); err != nil {
		log.Fatal(err.Error())
	}

	//inyectar nuestras dependencias.
	fraseStore := store.New(db)
	fraseService := service.New(fraseStore)
	fraseHandler := transport.New(fraseService)

	// configurar las rutas
	mux := http.NewServeMux()
	mux.HandleFunc("/frases", fraseHandler.HandleFrases)
	mux.HandleFunc("/frases/", fraseHandler.HandleFrasePorID)
	mux.HandleFunc("/frases/random", fraseHandler.HandleFraseRandom)

	if driver != "pgx" {
		dbPath, err := filepath.Abs("./frases.db")
		if err == nil {
			fmt.Println("💾 Base de datos en:", dbPath)
		}
	} else {
		fmt.Println("💾 Base de datos: Postgres (DATABASE_URL)")
	}

	fmt.Println("🚀 Servidor ejecutandose en http://localhost:8000")
	fmt.Println("📡 API Endpoints:")
	fmt.Println("📂 GET /frases         -Obtener todas las frases")
	fmt.Println("📂 GET /frases/random         -Obtener una frase random")
	fmt.Println("📝 POST /frases        -Crear una nueva frase")
	fmt.Println("🔍 GET /frases/{id}    -Obtener un libro especifico")
	fmt.Println("✏️  PUT /frases/{id}    -Actualizar una frase")
	fmt.Println("🗑️  DELETE /frases/{id} -Eliminar una frase")

	//empezar y escuchar al servidor
	log.Fatal(http.ListenAndServe(":8000", transport.WithCors(os.Getenv("CORS_ALLOWED_ORIGINS"), mux)))
}
