package main

import (
	"aprende-golang/internal/service"
	"aprende-golang/internal/store"
	"aprende-golang/internal/transport"
	"context"
	"database/sql"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
	_ "github.com/mattn/go-sqlite3"

	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
)

func main() {
	//conectar a la base: DATABASE_URL definida → Postgres (Render), sin definir → SQLite local
	dsn := os.Getenv("DATABASE_URL")
	driver := "sqlite3"
	if dsn == "" {
		// WAL + busy_timeout vía DSN: evita corrupción y contienda de locks (hallazgo 11)
		dsn = "./frases.db?_journal_mode=WAL&_busy_timeout=5000"
	} else {
		driver = "pgx"
	}
	db, err := sql.Open(driver, dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	// pooling acotado por motor (hallazgo 11): SQLite escribe serializado → 1 conexión; PG → pool acotado
	if driver == "pgx" {
		db.SetMaxOpenConns(10)
		db.SetMaxIdleConns(5)
		db.SetConnMaxLifetime(30 * time.Minute)
	} else {
		db.SetMaxOpenConns(1)
		db.SetMaxIdleConns(1)
	}

	//fallar rápido si la base no responde (5s)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := db.PingContext(ctx); err != nil {
		if os.Getenv("DATABASE_URL") != "" {
			log.Fatalf("no se pudo conectar a Postgres (DATABASE_URL): %v", err)
		}
		log.Fatalf("no se pudo conectar a SQLite (./frases.db): %v", err)
	}

	//crear el table si no existe.
	var q string
	if driver == "pgx" {
		q = `
			CREATE TABLE IF NOT EXISTS frases (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			frase TEXT NOT NULL,
			original TEXT NOT NULL,
			autor TEXT NOT NULL,
			categoria TEXT NOT NULL
		)
	`
	} else {
		q = `
			CREATE TABLE IF NOT EXISTS frases (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			frase TEXT NOT NULL,
			original TEXT NOT NULL,
			autor TEXT NOT NULL,
			categoria TEXT NOT NULL
		)
	`
	}
	if _, err := db.Exec(q); err != nil {
		log.Fatal(err.Error())
	}

	//inyectar nuestras dependencias.
	fraseStore := store.New(db)
	fraseService := service.New(fraseStore)
	fraseHandler := transport.New(fraseService)

	// configurar las rutas
	mux := http.NewServeMux()
	mux.HandleFunc("/frases", fraseHandler.HandleFrases)
	mux.HandleFunc("/frases/", fraseHandler.HandleFrasePorID)
	mux.HandleFunc("/frases/random", fraseHandler.HandleFraseRandom)

	if driver != "pgx" {
		dbPath, err := filepath.Abs("./frases.db")
		if err == nil {
			fmt.Println("💾 Base de datos en:", dbPath)
		}
	} else {
		fmt.Println("💾 Base de datos: Postgres (DATABASE_URL)")
	}

	fmt.Println("🚀 Servidor ejecutandose en http://localhost:8000")
	fmt.Println("📡 API Endpoints:")
	fmt.Println("📂 GET /frases         -Obtener todas las frases")
	fmt.Println("📂 GET /frases/random         -Obtener una frase random")
	fmt.Println("📝 POST /frases        -Crear una nueva frase")
	fmt.Println("🔍 GET /frases/{id}    -Obtener un libro especifico")
	fmt.Println("✏️  PUT /frases/{id}    -Actualizar una frase")
	fmt.Println("🗑️  DELETE /frases/{id} -Eliminar una frase")

	//servidor con timeouts (hallazgo 10) y apagado graceful ante señales
	srv := &http.Server{
		Addr:              ":8000",
		Handler:           transport.WithCors(os.Getenv("CORS_ALLOWED_ORIGINS"), mux),
		ReadTimeout:       10 * time.Second,
		ReadHeaderTimeout: 5 * time.Second,
		WriteTimeout:      10 * time.Second,
		IdleTimeout:       60 * time.Second,
	}

	go func() {
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("servidor: %v", err)
		}
	}()

	sigCtx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	<-sigCtx.Done()
	log.Println("apagando servidor...")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Printf("shutdown forzado: %v", err)
	}
}
